### PR TITLE
Do not take down stream and remove listener

### PR DESCRIPTION
**Pull request by macpie**

### CODE REVIEW

**Comment by Vagabond** [comment]
I think the other half of this is to obtain a *new* circuit address via the relay server?

**Comment by madninja** [comment]
@macpie I think the log is pointing out some valid errors here

**Comment by macpie** [comment]
what do you mean?

**Comment by madninja** [comment]
> what do you mean?

Check out the build logs in buildkite (clicks the Details link above). There are a few errors in there and I think at least one of those is a valid issue, not some transient network error

**Comment by macpie** [comment]
seems like buildkite is passing now

**Pull request merged**
